apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rehabilita-ingress
  namespace: rehabilita
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rehabilita.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rehabilita-service
            port:
              number: 80
